# Generated by Django 5.0.2 on 2024-02-27 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
                ('user_category', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('availability', models.IntegerField()),
                ('sale_qty', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
                ('packet_size', models.FloatField()),
                ('uom', models.CharField(max_length=10)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('min_rating', models.FloatField()),
                ('max_rating', models.FloatField()),
                ('avg_rating', models.FloatField()),
                ('qa_count', models.IntegerField()),
                ('best_by', models.DateField()),
                ('package_dimension', models.TextField()),
                ('package_dimension_unit', models.CharField(max_length=10)),
                ('ingredients', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenonicsapp.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenonicsapp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Additional'), ('this_order_only', 'This Order Only')], default='additional', max_length=20)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('address_line_3', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to='greenonicsapp.userdetails')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='greenonicsa_user_id_6d2c27_idx')],
            },
        ),
    ]
