# Generated by Django 5.0.2 on 2024-02-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0007_rename_images_product_additional_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.AddField(
            model_name='product',
            name='packet_size_uom',
            field=models.CharField(blank=True, choices=[('kg', 'KG'), ('g', 'G'), ('oz', 'OZ')], default='kg', max_length=10),
        ),
    ]
