# Generated by Django 5.0.2 on 2024-02-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0008_remove_product_expiry_date_remove_product_uom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(editable=False),
        ),
    ]
