# Generated by Django 5.0.2 on 2024-02-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0009_alter_product_sale_qty_alter_product_stock_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='qa_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
