# Generated by Django 5.0.2 on 2024-02-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0010_alter_product_avg_rating_alter_product_max_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packet_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
