# Generated by Django 5.0.2 on 2024-02-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0011_alter_product_packet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
