# Generated by Django 5.0.2 on 2024-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0013_remove_deliveryaddress_greenonicsa_user_id_6d2c27_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='deliveryaddress',
            index=models.Index(fields=['user'], name='greenonicsa_user_id_6d2c27_idx'),
        ),
    ]
