# Generated by Django 5.0.2 on 2024-03-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0014_deliveryaddress_greenonicsa_user_id_6d2c27_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaster',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('expedited', 'Expedited'), ('xpresspost', 'Xpresspost')], max_length=25),
        ),
    ]
