# Generated by Django 5.0.2 on 2024-03-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenonicsapp', '0015_ordermaster_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaster',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('expedited', 'Expedited'), ('xpresspost', 'Xpresspost')], default='free', max_length=25),
        ),
    ]
